// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class md_addcustomerid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(md_addcustomerid));
        
        string IMigrationMetadata.Id
        {
            get { return "202004051003390_md_addcustomerid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
