// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class WaterManualRecords_LastRecordDate_optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WaterManualRecords_LastRecordDate_optional));
        
        string IMigrationMetadata.Id
        {
            get { return "202103011257379_WaterManualRecords_LastRecordDate_optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
