// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class change_tables_10_17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_tables_10_17));
        
        string IMigrationMetadata.Id
        {
            get { return "202110171137043_change_tables_10_17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
