// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_HasSend_Billhead : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_HasSend_Billhead));
        
        string IMigrationMetadata.Id
        {
            get { return "202103271256395_add_HasSend_Billhead"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
