// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_LastWater_WaterMeter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_LastWater_WaterMeter));
        
        string IMigrationMetadata.Id
        {
            get { return "202103011148423_add_LastWater_WaterMeter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
