// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class change_Precision_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_Precision_3));
        
        string IMigrationMetadata.Id
        {
            get { return "202103210259463_change_Precision_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
