// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class chagne_optional_dt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chagne_optional_dt));
        
        string IMigrationMetadata.Id
        {
            get { return "202102201229076_chagne_optional_dt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
