// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_TotalChineseAmount_BillHeader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_TotalChineseAmount_BillHeader));
        
        string IMigrationMetadata.Id
        {
            get { return "202103271227132_add_TotalChineseAmount_BillHeader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
